name: Integration Test

on: [push]

jobs:
  compute_matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.supported-version.outputs.matrix }}
    steps:
      - uses: mage-os/github-actions/supported-version@main
        id: supported-version
        with:
          kind: latest
      - run: echo ${{ steps.supported-version.outputs.matrix }}

  integration-workflow:
    needs: compute_matrix
    uses: mage-os/github-actions/.github/workflows/integration.yaml@main
    with:
      package_name: vendic/magento2-postnl-api
      matrix: ${{ needs.compute_matrix.outputs.matrix }}
      test_command: ../../../vendor/bin/phpunit ../../../vendor/vendic/magento2-postnl-api/Test/Integration
      fail-fast: false
